# Generated by Django 5.2.5 on 2025-08-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ownner',
            new_name='owner',
        ),
    ]
