# Generated by Django 5.2.5 on 2025-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_ownner_movie_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique_for_date='created_at'),
        ),
    ]
